### ISSUE TITLE
Atomic Swaps. Проектирование

### ISSUE THREAD

**Issue by ishmelev23** [u-transnet/utransnet-core#3]
Спроектировать реализацию Atomic Swap для transnet-core.
Результатом должно быть:
1) описание программных компонентов необходимых для реализации;
2) последовательность шагов необходимых для реализации;
3) создание issues для задач и отражение их в доске проекта с пометками blocked, blocking.

Выполнение каждого шага должно сопровождаться кодом.

PS: первоначальная проработка вопроса доступна в [проекте](https://github.com/u-transnet/core-lab/projects/3)

**Comment by ishmelev23** [comment]
ПЕРЕВОД |  
-- | --
От | superpchelka23
Кому | utd-front
Количество | 62.50000 UTDEV.SKILL
Примечание | https://github.com/u-transnet/transnet-core/issues/3 Atomic Swaps. Проектирование. Окончание 09.02.2018, утро.

**Comment by ishmelev23** [comment]
@kkrupovich задача завершена, все задания на доске.

**Comment by cptn-solo** [comment]
@netral23 
BLOCK #24401757

TRANSFER |  
-- | --
From | utd-front
To | superpchelka23
Quantity | 62.50000 UTDEV
